### ISSUE TITLE
Format erro 

### ISSUE THREAD

**Issue by darknessdocetw** [darknessdocetw/Test2#1]
ActionController::UnknownFormat in EventsController#index

content:
 def index
        @events = Event.page(params[:page]).per(5)
         respond_to do |format|
            format.html 
            format.xml { render :xml => @events.to_xml }
            format.json { render :json => @events.to_json }
            format.atom { @feed_title = "My event list" } # index.atom.builder
         end
    end

**Comment by darknessforcetw** [comment]
#2 
修改app/controllers/events_controller.rb，將create Action和destroy Action裡的redirect_to改成

redirect_to events_url
